// SPDX-FileCopyrightText: Copyright 2024 shadPS4 Emulator Project
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

#include <array>
#include <cstring>
#include <span>
#include <vector>
#include <boost/container/static_vector.hpp>
#include "common/assert.h"
#include "common/types.h"
#include "shader_recompiler/backend/bindings.h"
#include "shader_recompiler/frontend/copy_shader.h"
#include "shader_recompiler/frontend/tessellation.h"
#include "shader_recompiler/ir/attribute.h"
#include "shader_recompiler/ir/passes/srt.h"
#include "shader_recompiler/ir/reg.h"
#include "shader_recompiler/ir/type.h"
#include "shader_recompiler/params.h"
#include "shader_recompiler/resource.h"
#include "shader_recompiler/runtime_info.h"

namespace Serialization {
struct Archive;
}

namespace Shader {

enum class Qualifier : u8 {
    None,
    Smooth,
    NoPerspective,
    PerVertex,
    Flat,
    Centroid,
    Sample,
};

/**
 * Contains general information generated by the shader recompiler for an input program.
 */
struct InfoPersistent {
    BufferResourceList buffers;
    ImageResourceList images;
    SamplerResourceList samplers;
    FMaskResourceList fmasks;

    u32 fetch_shader_sgpr_base{};
    u32 shared_memory_scratch_size{};

    u64 pgm_hash{};

    s32 tess_consts_dword_offset = -1;
    IR::ScalarReg tess_consts_ptr_base = IR::ScalarReg::Max;
    HwStage hw_stage;
    SwStage sw_stage;

    u8 mrt_mask{};
    bool has_fetch_shader{};
    bool has_bitwise_xor{};
    bool uses_dma{};

    InfoPersistent() = default;
    InfoPersistent(HwStage hw_stage_, SwStage sw_stage_, u64 pgm_hash_)
        : hw_stage{hw_stage_}, sw_stage{sw_stage_}, pgm_hash{pgm_hash_} {}
};

struct Info : InfoPersistent {
    struct AttributeFlags {
        bool Get(IR::Attribute attrib, u32 comp = 0) const {
            return flags[Index(attrib)] & (1 << comp);
        }

        bool GetAny(IR::Attribute attrib) const {
            return flags[Index(attrib)];
        }

        void Set(IR::Attribute attrib, u32 comp = 0) {
            flags[Index(attrib)] |= (1 << comp);
        }

        u32 NumComponents(IR::Attribute attrib) const {
            return 4;
        }

        static size_t Index(IR::Attribute attrib) {
            return static_cast<size_t>(attrib);
        }

        std::array<u8, IR::NumAttributes> flags;
    };

    enum class ReadConstType {
        None = 0,
        Immediate = 1 << 0,
        Dynamic = 1 << 1,
    };

    struct Interpolation {
        Qualifier primary;
        Qualifier auxiliary;
    };

    std::span<const u32> user_data;
    std::vector<u32> flattened_ud_buf;
    PersistentSrtInfo srt_info;

    AttributeFlags loads{};
    AttributeFlags stores{};

    ReadConstType readconst_types{};
    CopyShaderData gs_copy_data;
    u32 uses_patches{};

    VAddr pgm_base;
    bool has_storage_images{};
    bool has_discard{};
    bool has_image_gather{};
    bool has_image_query{};
    bool has_flatbuf{};
    bool uses_buffer_atomic_float_min_max{};
    bool uses_image_atomic_float_min_max{};
    bool uses_lane_id{};
    bool uses_shader_clock{};
    bool uses_group_quad{};
    bool uses_group_shuffle{};
    bool uses_group_ballot{};
    IR::Type shared_types{};
    bool uses_fp16{};
    bool uses_fp64{};
    bool uses_pack_10_11_11{};
    bool uses_unpack_10_11_11{};
    bool uses_buffer_int64_atomics{};
    bool uses_shared_int64_atomics{};
    bool stores_tess_level_outer{};
    bool stores_tess_level_inner{};
    bool translation_failed{};

    std::array<Interpolation, IR::NumParams> fs_interpolation{};

    Info() = default;
    Info(HwStage stage_, SwStage l_stage_, ShaderParams params)
        : InfoPersistent(stage_, l_stage_, params.hash), pgm_base{params.Base()},
          user_data{params.user_data} {}

    /// Threaded renderer: the draw recording thread runs a draw after the GPU command thread has
    /// moved on, and the pipeline cache refreshes user_data/flattened_ud_buf/pgm_base of the
    /// shared Info for every draw. The recording thread installs copies taken when the draw was
    /// queued; on any other thread (or with none installed) the members are used directly.
    struct UdSnapshot {
        const Info* info;
        const u32* user_data;
        u32 user_data_size;
        const u32* flat;
        u32 flat_size;
        VAddr pgm_base;
    };
    static constexpr u32 MaxUdSnapshots = 8;
    static inline thread_local std::array<UdSnapshot, MaxUdSnapshots> ud_snapshots{};
    static inline thread_local u32 num_ud_snapshots = 0;

    [[nodiscard]] const UdSnapshot* Snapshot() const noexcept {
        for (u32 i = 0; i < num_ud_snapshots; ++i) {
            if (ud_snapshots[i].info == this) {
                return &ud_snapshots[i];
            }
        }
        return nullptr;
    }
    [[nodiscard]] std::span<const u32> UserData() const noexcept {
        if (num_ud_snapshots != 0) [[unlikely]] {
            if (const auto* s = Snapshot()) {
                return {s->user_data, s->user_data_size};
            }
        }
        return user_data;
    }
    [[nodiscard]] std::span<const u32> FlatUserData() const noexcept {
        if (num_ud_snapshots != 0) [[unlikely]] {
            if (const auto* s = Snapshot()) {
                return {s->flat, s->flat_size};
            }
        }
        return flattened_ud_buf;
    }
    [[nodiscard]] VAddr ProgramBase() const noexcept {
        if (num_ud_snapshots != 0) [[unlikely]] {
            if (const auto* s = Snapshot()) {
                return s->pgm_base;
            }
        }
        return pgm_base;
    }

    template <typename T>
    inline T ReadUdSharp(u32 sharp_idx) const noexcept {
        return *reinterpret_cast<const T*>(&FlatUserData()[sharp_idx]);
    }

    template <typename T>
    T ReadUdReg(u32 ptr_index, u32 dword_offset) const noexcept {
        T data;
        const auto ud = UserData();
        const u32* base = ud.data();
        if (ptr_index != IR::NumScalarRegs) {
            std::memcpy(&base, &ud[ptr_index], sizeof(base));
            base = reinterpret_cast<const u32*>(VAddr(base) & 0xFFFFFFFFFFFFULL);
        }
        std::memcpy(&data, base + dword_offset, sizeof(T));
        return data;
    }

    void AddBindings(Backend::Bindings& bnd) const {
        bnd.buffer += buffers.size();
        bnd.unified += buffers.size() + images.size() + samplers.size();
    }

    void RefreshFlatBuf() {
        flattened_ud_buf.resize(srt_info.flattened_bufsize_dw);
        ASSERT(user_data.size() <= NUM_USER_DATA_REGS);
        std::memcpy(flattened_ud_buf.data(), user_data.data(), user_data.size_bytes());
        if (srt_info.walker_func) {
            srt_info.walker_func(user_data.data(), flattened_ud_buf.data());
        }
    }

    void ReadTessConstantBuffer(TessellationDataConstantBuffer& tess_constants) const {
        ASSERT(tess_consts_dword_offset >= 0); // We've already tracked the V# UD
        auto buf = ReadUdReg<AmdGpu::Buffer>(static_cast<u32>(tess_consts_ptr_base),
                                             static_cast<u32>(tess_consts_dword_offset));
        VAddr tess_constants_addr = buf.base_address;
        memcpy(&tess_constants,
               reinterpret_cast<TessellationDataConstantBuffer*>(tess_constants_addr),
               sizeof(tess_constants));
    }

    void Serialize(Serialization::Archive& ar) const;
    bool Deserialize(Serialization::Archive& ar);
};
DECLARE_ENUM_FLAG_OPERATORS(Info::ReadConstType);

} // namespace Shader
