// SPDX-FileCopyrightText: Copyright 2026 IFreemz
// SPDX-License-Identifier: GPL-2.0-or-later

#include <algorithm>
#include <atomic>
#include <chrono>
#include <filesystem>
#include <limits>
#include <mutex>

#include "common/logging/log.h"
#include "video_core/renderer_vulkan/vk_bb_fsr_frame_gen.h"
#include "video_core/renderer_vulkan/vk_fsr_upscaler.h"

#ifdef _WIN32
#define WIN32_LEAN_AND_MEAN
#define NOMINMAX
#include <ffx_api/ffx_framegeneration.h>
#include <ffx_api/vk/ffx_api_vk.h>
#include <windows.h>
#define BB_FSR_FRAME_GEN 1
#endif

namespace Vulkan::FsrFrameGen {

namespace {
bool selected{};
std::string problem;
} // namespace

void Select() {
    selected = true;
    LOG_INFO(Render_Vulkan, "[FSR-FG] FSR frame generation selected");
}

bool Selected() {
    return selected;
}

std::string Problem() {
    return problem;
}

#ifdef BB_FSR_FRAME_GEN

namespace {
struct Api {
    HMODULE module{};
    PfnFfxCreateContext create{};
    PfnFfxDestroyContext destroy{};
    PfnFfxConfigure configure{};
    PfnFfxQuery query{};
    PfnFfxDispatch dispatch{};
};
Api api;
bool active{};

vk::PhysicalDevice physical_device;
vk::Device device;
VkQueueInfoFFXAPI game{}, present{}, acquire{}, compute{};

// The swapchain context and the functions that replace the swapchain's.
ffxContext swapchain_context{};
ffxQueryDescSwapchainReplacementFunctionsVK functions{};
VkSwapchainKHR current_swapchain{};
VkFormat current_format{};

// Presenter thread state.
ffxContext context{};
vk::Extent2D context_display{}, context_render{};
VkFormat context_format{};
bool context_inverted{};
u64 frame_id{};
bool configured_on{};
std::chrono::steady_clock::time_point last_frame{};
u64 last_present_count{};

void Fail(std::string reason) {
    LOG_WARNING(Render_Vulkan, "[FSR-FG] Off: {}", reason);
    problem = std::move(reason);
    active = false;
}

FfxApiResource Image(vk::Image image, vk::Format format, vk::Extent2D extent, uint32_t state) {
    FfxApiResource resource{};
    resource.resource = reinterpret_cast<void*>(static_cast<VkImage>(image));
    resource.description.type = FFX_API_RESOURCE_TYPE_TEXTURE2D;
    resource.description.format = ffxApiGetSurfaceFormatVK(static_cast<VkFormat>(format));
    resource.description.width = extent.width;
    resource.description.height = extent.height;
    resource.description.depth = 1;
    resource.description.mipCount = 1;
    resource.description.flags = FFX_API_RESOURCE_FLAGS_NONE;
    resource.description.usage = FFX_API_RESOURCE_USAGE_READ_ONLY;
    resource.state = state;
    return resource;
}

ffxReturnCode_t DispatchGeneration(ffxDispatchDescFrameGeneration* params, void* user) {
    // FFX's swapchain passes scRGB (RenoDX HDR) with a luminance range of 0..0, which leaves
    // the UI found by comparing with the HUD-less image out of the generated frames.
    if (params->backbufferTransferFunction == FFX_API_BACKBUFFER_TRANSFER_FUNCTION_SCRGB &&
        params->minMaxLuminance[1] <= 0.f) {
        params->minMaxLuminance[0] = 0.f;
        params->minMaxLuminance[1] = 1000.f;
    }
    return api.dispatch(static_cast<ffxContext*>(user), &params->header);
}

void DestroyContext() {
    if (!context)
        return;
    // The swapchain may still present frames generated by it.
    (void)device.waitIdle();
    api.destroy(&context, nullptr);
    context = {};
    configured_on = false;
}

bool EnsureContext(vk::Extent2D display, vk::Extent2D render, bool inverted) {
    if (context && context_display == display && context_format == current_format &&
        context_inverted == inverted && render.width <= context_render.width &&
        render.height <= context_render.height)
        return true;
    DestroyContext();
    ffxCreateBackendVKDesc backend{};
    backend.header.type = FFX_API_CREATE_CONTEXT_DESC_TYPE_BACKEND_VK;
    backend.vkDevice = device;
    backend.vkPhysicalDevice = physical_device;
    backend.vkDeviceProcAddr =
        reinterpret_cast<PFN_vkGetDeviceProcAddr>(FsrUpscaler::FfxDeviceProcAddr());
    ffxCreateContextDescFrameGenerationHudless hudless{};
    hudless.header.type = FFX_API_CREATE_CONTEXT_DESC_TYPE_FRAMEGENERATION_HUDLESS;
    hudless.hudlessBackBufferFormat = ffxApiGetSurfaceFormatVK(current_format);
    backend.header.pNext = &hudless.header;
    ffxCreateContextDescFrameGeneration create{};
    create.header.type = FFX_API_CREATE_CONTEXT_DESC_TYPE_FRAMEGENERATION;
    create.header.pNext = &backend.header;
    create.flags = inverted ? FFX_FRAMEGENERATION_ENABLE_DEPTH_INVERTED : 0u;
    // An scRGB swapchain (RenoDX HDR) holds values above 1.
    if (current_format == VK_FORMAT_R16G16B16A16_SFLOAT)
        create.flags |= FFX_FRAMEGENERATION_ENABLE_HIGH_DYNAMIC_RANGE;
    create.displaySize = {display.width, display.height};
    // Room for the render size growing with a resolution patch change.
    const vk::Extent2D max_render{std::max(render.width, display.width),
                                  std::max(render.height, display.height)};
    create.maxRenderSize = {max_render.width, max_render.height};
    create.backBufferFormat = ffxApiGetSurfaceFormatVK(current_format);
    const auto result = api.create(&context, &create.header, nullptr);
    if (result != FFX_API_RETURN_OK) {
        context = {};
        LOG_ERROR(Render_Vulkan, "[FSR-FG] Context creation failed ({})", result);
        return false;
    }
    context_display = display;
    context_render = max_render;
    context_format = current_format;
    context_inverted = inverted;
    LOG_INFO(Render_Vulkan, "[FSR-FG] Context {}x{} (render up to {}x{})", display.width,
             display.height, max_render.width, max_render.height);
    return true;
}
} // namespace

bool PlanQueues(vk::Instance instance, vk::PhysicalDevice physical, u32 graphics_family,
                QueuePlan& plan) {
    const auto families = physical.getQueueFamilyProperties();
    // vkGetPhysicalDeviceWin32PresentationSupportKHR, from VK_KHR_win32_surface.
    using PresentationSupport = VkBool32(VKAPI_PTR*)(VkPhysicalDevice, uint32_t);
    const auto presentation_support = reinterpret_cast<PresentationSupport>(
        instance.getProcAddr("vkGetPhysicalDeviceWin32PresentationSupportKHR"));
    std::vector<u32> used(families.size());
    used[graphics_family] = 1; // the emulator's queue
    const auto take = [&](auto&& wanted, bool prefer_other_family) -> QueuePlan::Slot {
        for (const bool other : {prefer_other_family, false}) {
            for (u32 family = 0; family < families.size(); ++family) {
                if (other && family == graphics_family)
                    continue;
                if (used[family] < families[family].queueCount && wanted(family))
                    return {family, used[family]++};
            }
            if (!prefer_other_family)
                break;
        }
        return {};
    };
    plan.present = take(
        [&](u32 family) {
            return presentation_support &&
                   presentation_support(static_cast<VkPhysicalDevice>(physical), family);
        },
        false);
    plan.acquire = take([](u32) { return true; }, true);
    plan.compute = take(
        [&](u32 family) {
            return bool(families[family].queueFlags & vk::QueueFlagBits::eCompute) &&
                   !(families[family].queueFlags & vk::QueueFlagBits::eGraphics);
        },
        false);
    if (plan.present.family == ~0u || plan.acquire.family == ~0u) {
        Fail("FSR frame generation needs a GPU with more than one queue that can present.");
        selected = false;
        return false;
    }
    LOG_INFO(Render_Vulkan, "[FSR-FG] Queues: present {}.{}, acquire {}.{}, compute {}.{}",
             plan.present.family, plan.present.index, plan.acquire.family, plan.acquire.index,
             int(plan.compute.family), plan.compute.index);
    return true;
}

void SetDevice(vk::PhysicalDevice physical, vk::Device device_, vk::Queue game_queue,
               u32 game_family, const QueuePlan& plan) {
    if (!selected)
        return;
    physical_device = physical;
    device = device_;
    const auto queue = [&](const QueuePlan::Slot& slot) {
        VkQueueInfoFFXAPI info{};
        if (slot.family != ~0u) {
            info.queue = device.getQueue(slot.family, slot.index);
            info.familyIndex = slot.family;
        }
        return info;
    };
    // The emulator's queue is only used inside vkQueuePresentKHR, which it calls under its
    // submit lock.
    game = {static_cast<VkQueue>(game_queue), game_family, nullptr};
    present = queue(plan.present);
    acquire = queue(plan.acquire);
    compute = queue(plan.compute);

    const auto path = []() {
        std::wstring buffer(MAX_PATH, L'\0');
        buffer.resize(GetModuleFileNameW(nullptr, buffer.data(), DWORD(buffer.size())));
        return std::filesystem::path{buffer}.parent_path() / L"amd_fidelityfx_vk.dll";
    }();
    api.module = LoadLibraryW(path.c_str());
    if (!api.module)
        return Fail("amd_fidelityfx_vk.dll is missing next to shadPS4.exe.");
    const auto get = [](auto& function, const char* name) {
        function = reinterpret_cast<std::remove_reference_t<decltype(function)>>(
            GetProcAddress(api.module, name));
        return function != nullptr;
    };
    if (!get(api.create, "ffxCreateContext") || !get(api.destroy, "ffxDestroyContext") ||
        !get(api.configure, "ffxConfigure") || !get(api.query, "ffxQuery") ||
        !get(api.dispatch, "ffxDispatch"))
        return Fail("amd_fidelityfx_vk.dll is missing entry points.");
    active = true;
    LOG_INFO(Render_Vulkan, "[FSR-FG] Ready");
}

bool Active() {
    return active;
}

void Shutdown() {
    if (!api.module)
        return;
    if (context) {
        api.destroy(&context, nullptr);
        context = {};
    }
    if (swapchain_context) {
        api.destroy(&swapchain_context, nullptr);
        swapchain_context = {};
    }
    active = false;
}

vk::Result CreateSwapchain(const vk::SwapchainCreateInfoKHR& info, vk::SwapchainKHR& swapchain) {
    const VkSwapchainCreateInfoKHR& create_info = info;
    VkSwapchainKHR handle{};
    if (!swapchain_context) {
        ffxCreateContextDescFrameGenerationSwapChainVK create{};
        create.header.type = FFX_API_CREATE_CONTEXT_DESC_TYPE_FGSWAPCHAIN_VK;
        create.physicalDevice = physical_device;
        create.device = device;
        create.swapchain = &handle;
        create.allocator = nullptr;
        create.createInfo = create_info;
        create.gameQueue = game;
        create.asyncComputeQueue = compute;
        create.presentQueue = present;
        create.imageAcquireQueue = acquire;
        const auto result = api.create(&swapchain_context, &create.header, nullptr);
        if (result != FFX_API_RETURN_OK) {
            swapchain_context = {};
            LOG_ERROR(Render_Vulkan, "[FSR-FG] Swapchain creation failed ({})", result);
            return vk::Result::eErrorInitializationFailed;
        }
        functions = {};
        functions.header.type = FFX_API_QUERY_DESC_TYPE_FGSWAPCHAIN_FUNCTIONS_VK;
        api.query(&swapchain_context, &functions.header);
        LOG_INFO(Render_Vulkan, "[FSR-FG] Swapchain {}x{}", create_info.imageExtent.width,
                 create_info.imageExtent.height);
    } else {
        const auto result = functions.pOutCreateSwapchainFFXAPI(device, &create_info, nullptr,
                                                                &handle, swapchain_context);
        if (result != VK_SUCCESS)
            return static_cast<vk::Result>(result);
    }
    swapchain = handle;
    current_swapchain = handle;
    current_format = create_info.imageFormat;
    last_present_count = functions.pOutGetLastPresentCountFFXAPI
                             ? functions.pOutGetLastPresentCountFFXAPI(handle)
                             : 0;
    return vk::Result::eSuccess;
}

void DestroySwapchain(vk::SwapchainKHR swapchain) {
    // The generation context presents to it.
    DestroyContext();
    if (functions.pOutDestroySwapchainFFXAPI)
        functions.pOutDestroySwapchainFFXAPI(device, swapchain, nullptr, swapchain_context);
    if (static_cast<VkSwapchainKHR>(swapchain) == current_swapchain)
        current_swapchain = {};
}

vk::Result GetSwapchainImages(vk::SwapchainKHR swapchain, std::vector<vk::Image>& images) {
    u32 count{};
    auto result = functions.pOutGetSwapchainImagesKHR(device, swapchain, &count, nullptr);
    if (result != VK_SUCCESS)
        return static_cast<vk::Result>(result);
    std::vector<VkImage> raw(count);
    result = functions.pOutGetSwapchainImagesKHR(device, swapchain, &count, raw.data());
    images.assign(raw.begin(), raw.begin() + count);
    return static_cast<vk::Result>(result);
}

vk::Result AcquireNextImage(vk::SwapchainKHR swapchain, vk::Semaphore semaphore, u32& index) {
    return static_cast<vk::Result>(functions.pOutAcquireNextImageKHR(
        device, swapchain, std::numeric_limits<u64>::max(), semaphore, VK_NULL_HANDLE, &index));
}

vk::Result Present(vk::Queue queue, const vk::PresentInfoKHR& info) {
    const VkPresentInfoKHR& present_info = info;
    return static_cast<vk::Result>(functions.pOutQueuePresentKHR(queue, &present_info));
}

void SetFrame(const FrameGen::FrameInputs* inputs, const FrameGen::OverlayInputs* overlays,
              vk::CommandBuffer command, vk::Extent2D backbuffer, vk::Rect2D game_area) {
    if (!active || !current_swapchain)
        return;
    const auto now = std::chrono::steady_clock::now();
    const float frame_ms = last_frame.time_since_epoch().count()
                               ? std::chrono::duration<float, std::milli>(now - last_frame).count()
                               : 16.7f;
    last_frame = now;
    if (inputs && !EnsureContext(backbuffer, inputs->render, inputs->depth_inverted))
        inputs = nullptr;
    if (!context)
        return;

    ++frame_id;
    ffxConfigureDescFrameGeneration config{};
    config.header.type = FFX_API_CONFIGURE_DESC_TYPE_FRAMEGENERATION;
    config.swapChain = current_swapchain;
    config.frameGenerationCallback = DispatchGeneration;
    config.frameGenerationCallbackUserContext = &context;
    config.frameGenerationEnabled = inputs != nullptr;
    config.allowAsyncWorkloads = false;
    if (inputs && overlays)
        config.HUDLessColor = Image(overlays->hudless, overlays->hudless_format, overlays->extent,
                                    FFX_API_RESOURCE_STATE_PIXEL_COMPUTE_READ);
    config.generationRect = {game_area.offset.x, game_area.offset.y, int(game_area.extent.width),
                             int(game_area.extent.height)};
    config.frameID = frame_id;
    if (inputs || configured_on) {
        const auto result = api.configure(&context, &config.header);
        if (result != FFX_API_RETURN_OK)
            LOG_WARNING(Render_Vulkan, "[FSR-FG] Configure failed ({})", result);
        if (bool(inputs) != configured_on)
            LOG_INFO(Render_Vulkan, "[FSR-FG] {}", inputs ? "On" : "Off");
        configured_on = inputs != nullptr;
    }
    if (!inputs)
        return;

    ffxDispatchDescFrameGenerationPrepareCameraInfo camera{};
    camera.header.type = FFX_API_DISPATCH_DESC_TYPE_FRAMEGENERATION_PREPARE_CAMERAINFO;
    std::copy_n(inputs->position.data(), 3, camera.cameraPosition);
    std::copy_n(inputs->up.data(), 3, camera.cameraUp);
    std::copy_n(inputs->right.data(), 3, camera.cameraRight);
    std::copy_n(inputs->forward.data(), 3, camera.cameraForward);
    ffxDispatchDescFrameGenerationPrepare prepare{};
    prepare.header.type = FFX_API_DISPATCH_DESC_TYPE_FRAMEGENERATION_PREPARE;
    prepare.header.pNext = &camera.header;
    prepare.frameID = frame_id;
    prepare.commandList = static_cast<VkCommandBuffer>(command);
    prepare.renderSize = {inputs->render.width, inputs->render.height};
    // Same conventions as the upscaler: jitter and motion in render pixels.
    prepare.jitterOffset = {inputs->jitter[0], inputs->jitter[1]};
    prepare.motionVectorScale = {1.0f, 1.0f};
    prepare.frameTimeDelta = frame_ms;
    prepare.cameraNear = inputs->near_plane;
    prepare.cameraFar = inputs->far_plane;
    prepare.cameraFovAngleVertical = inputs->fov_y;
    prepare.viewSpaceToMetersFactor = 1.0f;
    prepare.depth = Image(inputs->depth, vk::Format::eR32Sfloat, inputs->render,
                          FFX_API_RESOURCE_STATE_PIXEL_COMPUTE_READ);
    prepare.motionVectors = Image(inputs->motion, vk::Format::eR16G16Sfloat, inputs->render,
                                  FFX_API_RESOURCE_STATE_PIXEL_COMPUTE_READ);
    const auto result = api.dispatch(&context, &prepare.header);
    if (result != FFX_API_RETURN_OK)
        LOG_WARNING(Render_Vulkan, "[FSR-FG] Prepare failed ({})", result);
}

u32 TakeShown() {
    if (!active || !current_swapchain || !functions.pOutGetLastPresentCountFFXAPI)
        return 1;
    const u64 count = functions.pOutGetLastPresentCountFFXAPI(current_swapchain);
    const u64 shown = count - last_present_count;
    last_present_count = count;
    return u32(std::min<u64>(shown, 8));
}

#else

bool PlanQueues(vk::Instance, vk::PhysicalDevice, u32, QueuePlan&) {
    selected = false;
    return false;
}
void SetDevice(vk::PhysicalDevice, vk::Device, vk::Queue, u32, const QueuePlan&) {}
bool Active() {
    return false;
}
void Shutdown() {}
vk::Result CreateSwapchain(const vk::SwapchainCreateInfoKHR&, vk::SwapchainKHR&) {
    return vk::Result::eErrorFeatureNotPresent;
}
void DestroySwapchain(vk::SwapchainKHR) {}
vk::Result GetSwapchainImages(vk::SwapchainKHR, std::vector<vk::Image>&) {
    return vk::Result::eErrorFeatureNotPresent;
}
vk::Result AcquireNextImage(vk::SwapchainKHR, vk::Semaphore, u32&) {
    return vk::Result::eErrorFeatureNotPresent;
}
vk::Result Present(vk::Queue, const vk::PresentInfoKHR&) {
    return vk::Result::eErrorFeatureNotPresent;
}
void SetFrame(const FrameGen::FrameInputs*, const FrameGen::OverlayInputs*, vk::CommandBuffer,
              vk::Extent2D, vk::Rect2D) {}
u32 TakeShown() {
    return 1;
}

#endif

} // namespace Vulkan::FsrFrameGen
